import {
  Class,
  ClassBlock,
  ClassException,
  ClassStudent,
  ScheduleConfig,
  Student,
  StudentSchedule,
  Teacher,
} from "@/types/schedule";

export const teachers: Teacher[] = [
  {
    id: "teacher-1",
    name: "김수학",
    subjects: ["수학", "물리"],
    phone: "010-1111-2222",
    email: "kim.math@academy.com",
  },
  {
    id: "teacher-2",
    name: "박영어",
    subjects: ["영어", "영문법"],
    phone: "010-3333-4444",
    email: "park.english@academy.com",
  },
  {
    id: "teacher-3",
    name: "이과학",
    subjects: ["화학", "생물"],
    phone: "010-5555-6666",
    email: "lee.science@academy.com",
  },
];

export const students: Student[] = [
  {
    id: 1,
    name: "정우진",
    grade: 11,
    phone: "010-1234-5678",
    parentPhone: "010-9876-5432",
    email: "woojin.jeong@example.com",
  },
  {
    id: 2,
    name: "김서윤",
    grade: 10,
    phone: "010-2345-6789",
    parentPhone: "010-8765-4321",
    email: "seoyoon.kim@example.com",
  },
  {
    id: 3,
    name: "이민서",
    grade: 9,
    phone: "010-3456-7890",
    parentPhone: "010-7654-3210",
    email: "minseo.lee@example.com",
  },
  {
    id: 4,
    name: "박하은",
    grade: 12,
    phone: "010-4567-8901",
    parentPhone: "010-6543-2109",
    email: "haeun.park@example.com",
  },
  {
    id: 5,
    name: "최도윤",
    grade: 10,
    phone: "010-5678-9012",
    parentPhone: "010-5432-1098",
    email: "doyoon.choi@example.com",
  },
  {
    id: 6,
    name: "강민규",
    grade: 8,
    phone: "010-6789-0123",
    parentPhone: "010-4321-0987",
    email: "mingyu.kang@example.com",
  },
  {
    id: 7,
    name: "조서현",
    grade: 11,
    phone: "010-7890-1234",
    parentPhone: "010-3210-9876",
    email: "seohyun.jo@example.com",
  },
  {
    id: 8,
    name: "윤지훈",
    grade: 12,
    phone: "010-8901-2345",
    parentPhone: "010-2109-8765",
    email: "jihun.yoon@example.com",
  },
  {
    id: 9,
    name: "송은서",
    grade: 7,
    phone: "010-9012-3456",
    parentPhone: "010-1098-7654",
    email: "eunseo.song@example.com",
  },
  {
    id: 10,
    name: "한준서",
    grade: 10,
    phone: "010-0123-4567",
    parentPhone: "010-0987-6543",
    email: "junseo.han@example.com",
  },
  {
    id: 11,
    name: "임유진",
    grade: 11,
    phone: "010-1122-3344",
    parentPhone: "010-9988-7766",
    email: "yujin.im@example.com",
  },
  {
    id: 12,
    name: "고민준",
    grade: 12,
    phone: "010-2233-4455",
    parentPhone: "010-8877-6655",
    email: "minjun.go@example.com",
  },
  {
    id: 13,
    name: "오지우",
    grade: 9,
    phone: "010-3344-5566",
    parentPhone: "010-7766-5544",
    email: "jiwoo.oh@example.com",
  },
  {
    id: 14,
    name: "노채은",
    grade: 10,
    phone: "010-4455-6677",
    parentPhone: "010-6655-4433",
    email: "chaeun.no@example.com",
  },
  {
    id: 15,
    name: "전수빈",
    grade: 11,
    phone: "010-5566-7788",
    parentPhone: "010-5544-3322",
    email: "subin.jeon@example.com",
  },
  {
    id: 16,
    name: "문태우",
    grade: 12,
    phone: "010-6677-8899",
    parentPhone: "010-4433-2211",
    email: "taewoo.moon@example.com",
  },
  {
    id: 17,
    name: "김서준",
    grade: 8,
    phone: "010-7788-9900",
    parentPhone: "010-3322-1100",
    email: "seojun.kim@example.com",
  },
  {
    id: 18,
    name: "박윤아",
    grade: 10,
    phone: "010-8899-0011",
    parentPhone: "010-2211-0099",
    email: "yoonah.park@example.com",
  },
  {
    id: 19,
    name: "이시우",
    grade: 11,
    phone: "010-9900-1122",
    parentPhone: "010-1100-9988",
    email: "siwoo.lee@example.com",
  },
  {
    id: 20,
    name: "정지은",
    grade: 12,
    phone: "010-0011-2233",
    parentPhone: "010-0099-8877",
    email: "jieun.jeong@example.com",
  },
  {
    id: 21,
    name: "최민서",
    grade: 7,
    phone: "010-1122-3344",
    parentPhone: "010-9988-7766",
    email: "minseo.choi@example.com",
  },
  {
    id: 22,
    name: "강유빈",
    grade: 10,
    phone: "010-2233-4455",
    parentPhone: "010-8877-6655",
    email: "yubin.kang@example.com",
  },
  {
    id: 23,
    name: "윤예원",
    grade: 11,
    phone: "010-3344-5566",
    parentPhone: "010-7766-5544",
    email: "yewon.yoon@example.com",
  },
  {
    id: 24,
    name: "조우진",
    grade: 12,
    phone: "010-4455-6677",
    parentPhone: "010-6655-4433",
    email: "woojin.jo@example.com",
  },
  {
    id: 25,
    name: "송서윤",
    grade: 9,
    phone: "010-5566-7788",
    parentPhone: "010-5544-3322",
    email: "seoyoon.song@example.com",
  },
];

export const classes: Class[] = [
  {
    id: "class-1",
    title: "중2 수학 A반",
    subject: "수학",
    teacherId: "teacher-1",
    teacherName: "김수학",
    startTime: "14:00",
    endTime: "15:30",
    dayOfWeek: 0, // 월요일
    color: "#3B82F6", // blue-500
    room: "A101",
    maxStudents: 15,
    description: "중학교 2학년 수학 기본반",
  },
  {
    id: "class-2",
    title: "중2 영어 초급반",
    subject: "영어",
    teacherId: "teacher-2",
    teacherName: "박영어",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2, // 수요일
    color: "#10B981", // emerald-500
    room: "B201",
    maxStudents: 12,
    description: "중학교 2학년 영어 초급반",
  },
  {
    id: "class-3",
    title: "중2 수학 B반",
    subject: "수학",
    teacherId: "teacher-1",
    teacherName: "김수학",
    startTime: "15:30",
    endTime: "17:00",
    dayOfWeek: 0, // 월요일
    color: "#3B82F6", // blue-500
    room: "A102",
    maxStudents: 15,
    description: "중학교 2학년 수학 심화반",
  },
  {
    id: "class-4",
    title: "중3 화학 실험반",
    subject: "화학",
    teacherId: "teacher-3",
    teacherName: "이과학",
    startTime: "19:00",
    endTime: "20:30",
    dayOfWeek: 4, // 금요일
    color: "#F59E0B", // amber-500
    room: "실험실",
    maxStudents: 8,
    description: "중학교 3학년 화학 실험반",
  },
  {
    id: "class-5",
    title: "중2 영어 중급반",
    subject: "영어",
    teacherId: "teacher-2",
    teacherName: "박영어",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 1, // 화요일
    color: "#10B981", // emerald-500
    room: "B202",
    maxStudents: 12,
    description: "중학교 2학년 영어 중급반",
  },
];

export const classStudents: ClassStudent[] = [
  {
    id: "cs-1",
    classId: "class-1",
    studentId: "student-1",
    enrolledDate: "2024-01-01",
    status: "active",
  },
  {
    id: "cs-2",
    classId: "class-1",
    studentId: "student-2",
    enrolledDate: "2024-01-01",
    status: "active",
  },
  {
    id: "cs-3",
    classId: "class-2",
    studentId: "student-1",
    enrolledDate: "2024-01-15",
    status: "active",
  },
  {
    id: "cs-4",
    classId: "class-3",
    studentId: "student-2",
    enrolledDate: "2024-02-01",
    status: "active",
  },
  {
    id: "cs-5",
    classId: "class-4",
    studentId: "student-3",
    enrolledDate: "2024-01-01",
    status: "active",
  },
  {
    id: "cs-6",
    classId: "class-5",
    studentId: "student-1",
    enrolledDate: "2024-02-15",
    status: "active",
  },
];

export const classExceptions: ClassException[] = [
  {
    id: "ex-1",
    classId: "class-1",
    date: "2024-09-01",
    type: "cancel",
    reason: "추석 연휴",
  },
  {
    id: "ex-2",
    classId: "class-2",
    date: "2024-09-15",
    type: "reschedule",
    reason: "강사 개인사정",
    newStartTime: "17:00",
    newEndTime: "18:30",
  },
];

export const studentSchedules: StudentSchedule[] = [
  {
    id: "ss-1",
    studentId: 1,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-2",
    studentId: 1,
    title: "수영 강습",
    description: "개인 수영 강습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "수영장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-3",
    studentId: 2,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-4",
    studentId: 2,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-5",
    studentId: 3,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-6",
    studentId: 3,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-7",
    studentId: 4,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-8",
    studentId: 4,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-9",
    studentId: 5,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-10",
    studentId: 5,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-11",
    studentId: 6,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-12",
    studentId: 6,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-13",
    studentId: 7,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-14",
    studentId: 7,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-15",
    studentId: 8,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-16",
    studentId: 8,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-17",
    studentId: 9,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-18",
    studentId: 9,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-19",
    studentId: 10,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-20",
    studentId: 10,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-21",
    studentId: 11,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-22",
    studentId: 11,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-23",
    studentId: 12,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-24",
    studentId: 12,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-25",
    studentId: 13,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-26",
    studentId: 13,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-27",
    studentId: 14,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-28",
    studentId: 14,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-29",
    studentId: 15,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-30",
    studentId: 15,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-31",
    studentId: 16,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-32",
    studentId: 16,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-33",
    studentId: 17,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-34",
    studentId: 17,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-35",
    studentId: 18,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-36",
    studentId: 18,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-37",
    studentId: 19,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-38",
    studentId: 19,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-39",
    studentId: 20,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-40",
    studentId: 20,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-41",
    studentId: 21,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-42",
    studentId: 21,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-43",
    studentId: 22,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-44",
    studentId: 22,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-45",
    studentId: 23,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-46",
    studentId: 23,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-47",
    studentId: 24,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-48",
    studentId: 24,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-49",
    studentId: 25,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-50",
    studentId: 25,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-51",
    studentId: 26,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-52",
    studentId: 26,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-53",
    studentId: 27,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-54",
    studentId: 27,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-55",
    studentId: 28,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-56",
    studentId: 28,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-57",
    studentId: 29,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-58",
    studentId: 29,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-59",
    studentId: 30,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-60",
    studentId: 30,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-61",
    studentId: 31,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-62",
    studentId: 31,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-63",
    studentId: 32,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-64",
    studentId: 32,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-65",
    studentId: 33,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-66",
    studentId: 33,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-67",
    studentId: 34,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-68",
    studentId: 34,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-69",
    studentId: 35,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-70",
    studentId: 35,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-71",
    studentId: 36,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-72",
    studentId: 36,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-73",
    studentId: 37,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-74",
    studentId: 37,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-75",
    studentId: 38,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-76",
    studentId: 38,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-77",
    studentId: 39,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-78",
    studentId: 39,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-79",
    studentId: 40,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-80",
    studentId: 40,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-81",
    studentId: 41,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-82",
    studentId: 41,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-83",
    studentId: 42,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-84",
    studentId: 42,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-85",
    studentId: 43,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-86",
    studentId: 43,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-87",
    studentId: 44,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-88",
    studentId: 44,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-89",
    studentId: 45,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-90",
    studentId: 45,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-91",
    studentId: 46,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-92",
    studentId: 46,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-93",
    studentId: 47,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-94",
    studentId: 47,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-95",
    studentId: 48,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-96",
    studentId: 48,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-97",
    studentId: 49,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-98",
    studentId: 49,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-99",
    studentId: 50,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-100",
    studentId: 50,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-101",
    studentId: 51,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-102",
    studentId: 51,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-103",
    studentId: 52,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-104",
    studentId: 52,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-105",
    studentId: 53,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-106",
    studentId: 53,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-107",
    studentId: 54,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-108",
    studentId: 54,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-109",
    studentId: 55,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-110",
    studentId: 55,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-111",
    studentId: 56,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-112",
    studentId: 56,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-113",
    studentId: 57,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-114",
    studentId: 57,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-115",
    studentId: 58,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-116",
    studentId: 58,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-117",
    studentId: 59,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-118",
    studentId: 59,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-119",
    studentId: 60,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-120",
    studentId: 60,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-121",
    studentId: 61,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-122",
    studentId: 61,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-123",
    studentId: 62,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-124",
    studentId: 62,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-125",
    studentId: 63,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-126",
    studentId: 63,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-127",
    studentId: 64,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-128",
    studentId: 64,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-129",
    studentId: 65,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-130",
    studentId: 65,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-131",
    studentId: 66,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-132",
    studentId: 66,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-133",
    studentId: 67,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-134",
    studentId: 67,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-135",
    studentId: 68,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-136",
    studentId: 68,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-137",
    studentId: 69,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-138",
    studentId: 69,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-139",
    studentId: 70,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-140",
    studentId: 70,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-141",
    studentId: 71,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-142",
    studentId: 71,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-143",
    studentId: 72,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-144",
    studentId: 72,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-145",
    studentId: 73,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-146",
    studentId: 73,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-147",
    studentId: 74,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-148",
    studentId: 74,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-149",
    studentId: 75,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-150",
    studentId: 75,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-151",
    studentId: 76,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-152",
    studentId: 76,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-153",
    studentId: 77,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-154",
    studentId: 77,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-155",
    studentId: 78,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-156",
    studentId: 78,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-157",
    studentId: 79,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-158",
    studentId: 79,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-159",
    studentId: 80,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-160",
    studentId: 80,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-161",
    studentId: 81,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-162",
    studentId: 81,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-163",
    studentId: 82,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-164",
    studentId: 82,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-165",
    studentId: 83,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-166",
    studentId: 83,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-167",
    studentId: 84,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-168",
    studentId: 84,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-169",
    studentId: 85,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-170",
    studentId: 85,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-171",
    studentId: 86,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-172",
    studentId: 86,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-173",
    studentId: 87,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-174",
    studentId: 87,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-175",
    studentId: 88,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-176",
    studentId: 88,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
  {
    id: "ss-177",
    studentId: 89,
    title: "중국어 회화",
    description: "그룹 중국어 회화",
    startTime: "18:00",
    endTime: "19:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "study",
    location: "외국어학원",
    recurring: true,
    createdDate: "2024-02-20",
    status: "active",
  },
  {
    id: "ss-178",
    studentId: 89,
    title: "복싱",
    description: "개인 복싱 훈련",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "복싱 체육관",
    recurring: true,
    createdDate: "2024-06-01",
    status: "active",
  },
  {
    id: "ss-179",
    studentId: 90,
    title: "요가",
    description: "성장 요가 수업",
    startTime: "16:00",
    endTime: "17:30",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "요가 스튜디오",
    recurring: true,
    createdDate: "2024-01-10",
    status: "active",
  },
  {
    id: "ss-180",
    studentId: 90,
    title: "기타 레슨",
    description: "통기타 초급",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#F97316",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-02-25",
    status: "active",
  },
  {
    id: "ss-181",
    studentId: 91,
    title: "축구 동아리",
    description: "축구 스킬 훈련",
    startTime: "17:00",
    endTime: "18:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-05",
    status: "active",
  },
  {
    id: "ss-182",
    studentId: 91,
    title: "입시 미술",
    description: "대학 입시 포트폴리오 준비",
    startTime: "19:30",
    endTime: "21:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "study",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-04-15",
    status: "active",
  },
  {
    id: "ss-183",
    studentId: 92,
    title: "바이올린 레슨",
    description: "개인 바이올린 레슨",
    startTime: "16:30",
    endTime: "17:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-184",
    studentId: 92,
    title: "토론 수업",
    description: "사회 이슈 토론",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 5,
    color: "#14B8A6",
    type: "study",
    location: "문화센터",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-185",
    studentId: 93,
    title: "필라테스",
    description: "체형 교정 필라테스",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "extracurricular",
    location: "필라테스 스튜디오",
    recurring: true,
    createdDate: "2024-05-01",
    status: "active",
  },
  {
    id: "ss-186",
    studentId: 93,
    title: "밴드 연습",
    description: "주말 밴드 연습",
    startTime: "20:00",
    endTime: "21:30",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "연습실",
    recurring: true,
    createdDate: "2024-06-10",
    status: "active",
  },
  {
    id: "ss-187",
    studentId: 94,
    title: "성악 레슨",
    description: "개인 성악 레슨",
    startTime: "17:30",
    endTime: "19:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "성악 스튜디오",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-188",
    studentId: 94,
    title: "체스 동아리",
    description: "전략 체스 학습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 4,
    color: "#EF4444",
    type: "extracurricular",
    location: "체스 클럽",
    recurring: true,
    createdDate: "2024-03-20",
    status: "active",
  },
  {
    id: "ss-189",
    studentId: 95,
    title: "클라리넷 레슨",
    description: "개인 클라리넷 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-190",
    studentId: 95,
    title: "테니스",
    description: "테니스 개인 코칭",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 3,
    color: "#14B8A6",
    type: "extracurricular",
    location: "테니스장",
    recurring: true,
    createdDate: "2024-02-01",
    status: "active",
  },
  {
    id: "ss-191",
    studentId: 96,
    title: "독서 모임",
    description: "문학 작품 토론",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 2,
    color: "#64748B",
    type: "study",
    location: "도서관",
    recurring: true,
    createdDate: "2024-04-01",
    status: "active",
  },
  {
    id: "ss-192",
    studentId: 96,
    title: "배드민턴",
    description: "배드민턴 클럽 활동",
    startTime: "20:30",
    endTime: "22:00",
    dayOfWeek: 6,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-10",
    status: "active",
  },
  {
    id: "ss-193",
    studentId: 97,
    title: "피아노 레슨",
    description: "개인 피아노 레슨",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-194",
    studentId: 97,
    title: "축구 훈련",
    description: "개인 축구 스킬 연습",
    startTime: "18:00",
    endTime: "19:30",
    dayOfWeek: 2,
    color: "#EF4444",
    type: "extracurricular",
    location: "운동장",
    recurring: true,
    createdDate: "2024-03-01",
    status: "active",
  },
  {
    id: "ss-195",
    studentId: 98,
    title: "태권도 수련",
    description: "품새와 겨루기",
    startTime: "17:30",
    endTime: "18:30",
    dayOfWeek: 1,
    color: "#06B6D4",
    type: "extracurricular",
    location: "태권도장",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-196",
    studentId: 98,
    title: "미술학원",
    description: "드로잉 수업",
    startTime: "19:00",
    endTime: "20:00",
    dayOfWeek: 4,
    color: "#14B8A6",
    type: "extracurricular",
    location: "미술학원",
    recurring: true,
    createdDate: "2024-02-15",
    status: "active",
  },
  {
    id: "ss-197",
    studentId: 99,
    title: "코딩 스터디",
    description: "파이썬 기초",
    startTime: "16:30",
    endTime: "18:00",
    dayOfWeek: 3,
    color: "#64748B",
    type: "study",
    location: "스터디카페",
    recurring: true,
    createdDate: "2024-04-10",
    status: "active",
  },
  {
    id: "ss-198",
    studentId: 99,
    title: "농구 훈련",
    description: "개인 농구 스킬 연습",
    startTime: "20:00",
    endTime: "21:00",
    dayOfWeek: 5,
    color: "#F97316",
    type: "extracurricular",
    location: "체육관",
    recurring: true,
    createdDate: "2024-05-20",
    status: "active",
  },
  {
    id: "ss-199",
    studentId: 100,
    title: "첼로 레슨",
    description: "개인 첼로 레슨",
    startTime: "17:00",
    endTime: "18:30",
    dayOfWeek: 0,
    color: "#8B5CF6",
    type: "extracurricular",
    location: "음악학원",
    recurring: true,
    createdDate: "2024-01-01",
    status: "active",
  },
  {
    id: "ss-200",
    studentId: 100,
    title: "과학 실험",
    description: "주말 과학 실험 교실",
    startTime: "16:00",
    endTime: "17:00",
    dayOfWeek: 6,
    color: "#EF4444",
    type: "extracurricular",
    location: "과학실험실",
    recurring: true,
    createdDate: "2024-03-10",
    status: "active",
  },
];

// 기본 시간표 설정
export const defaultScheduleConfig: ScheduleConfig = {
  startHour: 9,
  endHour: 24,
  timeSlotMinutes: 10,
  showWeekend: true,
  firstDayOfWeek: 1, // 월요일 시작
};

// 더미 ClassBlock 데이터 생성 함수
export function generateClassBlocks(): ClassBlock[] {
  return classes.map((cls) => {
    const studentsInClass = classStudents.filter(
      (cs) => cs.classId === cls.id && cs.status === "active"
    );

    return {
      id: cls.id,
      classId: cls.id,
      title: cls.title,
      subject: cls.subject,
      teacherName: cls.teacherName,
      startTime: cls.startTime,
      endTime: cls.endTime,
      dayOfWeek: cls.dayOfWeek,
      color: cls.color,
      room: cls.room,
      studentCount: studentsInClass.length,
      maxStudents: cls.maxStudents,
    };
  });
}

// 시간대별 학생 일정 밀집도 계산 함수
export function calculateStudentDensity(config: ScheduleConfig) {
  const timeSlots: { [key: string]: number } = {};
  
  // 모든 시간 슬롯 초기화
  for (let day = 0; day < 7; day++) {
    for (let hour = config.startHour; hour <= config.endHour; hour++) {
      for (let minute = 0; minute < 60; minute += config.timeSlotMinutes) {
        const time = `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
        const key = `${day}-${time}`;
        timeSlots[key] = 0;
      }
    }
  }

  // 학생 일정 카운트
  studentSchedules.forEach(schedule => {
    if (schedule.status !== 'active') return;
    
    const startHour = parseInt(schedule.startTime.split(':')[0]);
    const startMinute = parseInt(schedule.startTime.split(':')[1]);
    const endHour = parseInt(schedule.endTime.split(':')[0]);
    const endMinute = parseInt(schedule.endTime.split(':')[1]);
    
    const startMinutes = startHour * 60 + startMinute;
    const endMinutes = endHour * 60 + endMinute;
    
    // 시작 시간부터 종료 시간까지 모든 슬롯에 카운트 추가
    for (let minutes = startMinutes; minutes < endMinutes; minutes += config.timeSlotMinutes) {
      const hour = Math.floor(minutes / 60);
      const minute = minutes % 60;
      const time = `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
      const key = `${schedule.dayOfWeek}-${time}`;
      
      if (timeSlots[key] !== undefined) {
        timeSlots[key]++;
      }
    }
  });

  return timeSlots;
}

// 밀집도에 따른 색상 계산 함수
export function getDensityColor(density: number, maxDensity: number): string {
  if (density === 0) return 'transparent';
  
  const ratio = density / maxDensity;
  
  if (ratio <= 0.3) {
    // 낮은 밀집도: 파랑 → 초록
    return `rgba(34, 197, 94, ${0.3 + ratio * 0.4})`; // green-500 기반
  } else if (ratio <= 0.7) {
    // 중간 밀집도: 초록 → 노랑
    return `rgba(234, 179, 8, ${0.4 + ratio * 0.3})`; // yellow-500 기반
  } else {
    // 높은 밀집도: 노랑 → 빨강
    return `rgba(239, 68, 68, ${0.5 + ratio * 0.4})`; // red-500 기반
  }
}

// 특정 시간대의 학생들 정보 가져오기 함수
export function getStudentsAtTime(dayOfWeek: number, time: string) {
  const studentsAtTime: Array<{ student: Student; schedule: StudentSchedule }> = [];
  
  const targetHour = parseInt(time.split(':')[0]);
  const targetMinute = parseInt(time.split(':')[1]);
  const targetMinutes = targetHour * 60 + targetMinute;
  
  studentSchedules.forEach(schedule => {
    if (schedule.status !== 'active' || schedule.dayOfWeek !== dayOfWeek) return;
    
    const startHour = parseInt(schedule.startTime.split(':')[0]);
    const startMinute = parseInt(schedule.startTime.split(':')[1]);
    const endHour = parseInt(schedule.endTime.split(':')[0]);
    const endMinute = parseInt(schedule.endTime.split(':')[1]);
    
    const startMinutes = startHour * 60 + startMinute;
    const endMinutes = endHour * 60 + endMinute;
    
    // 해당 시간이 일정 시간 범위에 포함되는지 확인
    if (targetMinutes >= startMinutes && targetMinutes < endMinutes) {
      const student = students.find(s => s.id === schedule.studentId);
      if (student) {
        studentsAtTime.push({ student, schedule });
      }
    }
  });
  
  return studentsAtTime;
}
