-- ZUKU 학원 관리 시스템 초기 스키마
-- 실행 순서: 1

-- 학생 정보 테이블
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    grade INT NOT NULL,
    phone TEXT,
    parent_phone TEXT,
    email TEXT
);

-- 강사 정보 테이블 (기본)
CREATE TABLE teachers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subjects TEXT[] NOT NULL,
    phone TEXT,
    email TEXT
);

-- 조교 정보 테이블 (기본)
CREATE TABLE assistants (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    teacher_id TEXT REFERENCES teachers(id) ON DELETE SET NULL,
    subjects TEXT[] NOT NULL,
    phone TEXT,
    email TEXT,
    assigned_grades INT[] NOT NULL
);

-- 수업 정보 테이블
CREATE TABLE classes (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    subject TEXT NOT NULL,
    teacher_id TEXT REFERENCES teachers(id) ON DELETE SET NULL,
    teacher_name TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    day_of_week INT NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    color TEXT NOT NULL,
    room TEXT,
    max_students INT,
    description TEXT,
    rrule TEXT
);

-- 수업 예외 정보 테이블 (휴강, 시간 변경 등)
CREATE TABLE class_exceptions (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('cancel', 'reschedule', 'substitute')),
    reason TEXT,
    new_start_time TIME,
    new_end_time TIME,
    new_room TEXT,
    substitute_teacher_id TEXT REFERENCES teachers(id) ON DELETE SET NULL
);

-- 수강 정보 테이블 (수업-학생 관계)
CREATE TABLE class_students (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    enrolled_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'paused', 'withdrawn')),
    UNIQUE(class_id, student_id)
);

-- 학생 개인 일정 테이블
CREATE TABLE student_schedules (
    id TEXT PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    day_of_week INT NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    color TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('personal', 'extracurricular', 'study', 'appointment', 'other')),
    location TEXT,
    recurring BOOLEAN,
    rrule TEXT,
    created_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'cancelled', 'completed'))
);

-- 중등 주간 기록 테이블 (강사 작성)
CREATE TABLE middle_school_records (
    id TEXT PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    teacher_id TEXT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    week_of DATE NOT NULL,
    attendance TEXT NOT NULL CHECK (attendance IN ('present', 'absent', 'late')),
    participation INT NOT NULL CHECK (participation >= 1 AND participation <= 5),
    understanding INT NOT NULL CHECK (understanding >= 1 AND understanding <= 5),
    homework TEXT NOT NULL CHECK (homework IN ('excellent', 'good', 'fair', 'poor', 'not_submitted')),
    notes TEXT NOT NULL,
    created_date DATE NOT NULL,
    last_modified DATE NOT NULL
);

-- 고등 숙제 검사 기록 테이블 (조교 작성)
CREATE TABLE high_school_homework_records (
    id TEXT PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    assistant_id TEXT NOT NULL REFERENCES assistants(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    homework_range TEXT NOT NULL,
    achievement TEXT NOT NULL CHECK (achievement IN ('excellent', 'good', 'fair', 'poor', 'not_submitted')),
    completion_rate INT NOT NULL CHECK (completion_rate >= 0 AND completion_rate <= 100),
    accuracy INT NOT NULL CHECK (accuracy >= 0 AND accuracy <= 100),
    notes TEXT,
    created_date DATE NOT NULL
);